CHAPTER_WEIGHT_MAPPINGS = {
    "simple_interest": {
        "concept_based": 10,
        "formula_based": 35,
        "calculation_based": 50,
        "reasoning_based": 5,
        "memory_based": 0,
        "diagram_based": 0,
        "data_interpretation_based": 0,
        "proof_or_derivation_based": 0,
        "application_based": 0,
        "language_or_explanation_based": 0,
    },
    "compound_interest": {
        "concept_based": 10,
        "formula_based": 35,
        "calculation_based": 50,
        "reasoning_based": 5,
        "memory_based": 0,
        "diagram_based": 0,
        "data_interpretation_based": 0,
        "proof_or_derivation_based": 0,
        "application_based": 0,
        "language_or_explanation_based": 0,
    },
    "mensuration": {
        "concept_based": 15,
        "formula_based": 35,
        "calculation_based": 45,
        "reasoning_based": 5,
        "memory_based": 0,
        "diagram_based": 0,
        "data_interpretation_based": 0,
        "proof_or_derivation_based": 0,
        "application_based": 0,
        "language_or_explanation_based": 0,
    },
    "photosynthesis": {
        "concept_based": 70,
        "formula_based": 0,
        "calculation_based": 0,
        "reasoning_based": 0,
        "memory_based": 20,
        "diagram_based": 0,
        "data_interpretation_based": 0,
        "proof_or_derivation_based": 0,
        "application_based": 0,
        "language_or_explanation_based": 10,
    },
    "grammar": {
        "concept_based": 40,
        "formula_based": 0,
        "calculation_based": 0,
        "reasoning_based": 0,
        "memory_based": 20,
        "diagram_based": 0,
        "data_interpretation_based": 0,
        "proof_or_derivation_based": 0,
        "application_based": 0,
        "language_or_explanation_based": 40,
    },
    "proof": {
        "concept_based": 25,
        "formula_based": 0,
        "calculation_based": 0,
        "reasoning_based": 20,
        "memory_based": 0,
        "diagram_based": 0,
        "data_interpretation_based": 0,
        "proof_or_derivation_based": 55,
        "application_based": 0,
        "language_or_explanation_based": 0,
    },
    "data_interpretation": {
        "concept_based": 5,
        "formula_based": 0,
        "calculation_based": 25,
        "reasoning_based": 20,
        "memory_based": 0,
        "diagram_based": 0,
        "data_interpretation_based": 50,
        "proof_or_derivation_based": 0,
        "application_based": 0,
        "language_or_explanation_based": 0,
    },
}
