QUESTION_ANALYSIS_RULES = [
    {
        "category": "calculation_based",
        "keywords": [
            "calculate",
            "find",
            "solve",
            "determine",
            "evaluate",
            "compute",
            "simplify",
        ],
        "score_boost": 30,
    },
    {
        "category": "formula_based",
        "keywords": [
            "area",
            "volume",
            "speed",
            "velocity",
            "force",
            "pressure",
            "work done",
            "simple interest",
            "compound interest",
            "probability",
            "percentage",
            "average",
            "ratio",
            "profit",
            "loss",
            "time",
            "distance",
            "rate",
            "principal",
            "amount",
            "acceleration",
            "perimeter",
            "circumference",
        ],
        "score_boost": 25,
    },
    {
        "category": "concept_based",
        "keywords": [
            "explain",
            "why",
            "describe",
            "difference between",
            "what is",
            "how",
            "principle",
            "reason",
            "law",
            "concept",
            "cause",
            "effect",
        ],
        "score_boost": 25,
    },
    {
        "category": "memory_based",
        "keywords": [
            "define",
            "state",
            "name",
            "list",
            "identify",
            "recall",
            "mention",
            "write",
            "who",
            "when",
            "where",
        ],
        "score_boost": 25,
    },
    {
        "category": "proof_or_derivation_based",
        "keywords": [
            "prove",
            "derive",
            "show that",
            "verify",
            "establish",
        ],
        "score_boost": 35,
    },
    {
        "category": "reasoning_based",
        "keywords": [
            "assertion",
            "reason",
            "compare",
            "analyze",
            "justify",
            "infer",
            "conclusion",
            "case",
            "situation",
            "if",
            "because",
            "which is correct",
            "choose the correct",
            "best explanation",
        ],
        "score_boost": 20,
    },
    {
        "category": "language_or_explanation_based",
        "keywords": [
            "explain in detail",
            "write a note",
            "describe",
            "essay",
            "paragraph",
            "long answer",
        ],
        "score_boost": 30,
    },
    {
        "category": "data_interpretation_based",
        "keywords": [
            "table",
            "chart",
            "graph",
            "data",
            "passage",
            "given below",
            "observe",
            "study the following",
        ],
        "score_boost": 35,
    },
    {
        "category": "diagram_based",
        "keywords": [
            "diagram",
            "figure",
            "image",
            "map",
            "circuit",
            "ray diagram",
            "draw",
            "label",
        ],
        "score_boost": 35,
    },
    {
        "category": "application_based",
        "keywords": [
            "real life",
            "daily life",
            "practical",
            "application",
            "case study",
            "situation based",
        ],
        "score_boost": 30,
    },
]
